### ISSUE TITLE
Debian 10 Stable pyo import error

### ISSUE THREAD

**Issue by davisrichard437** [belangeo/cecilia5#104]
I'm rather new to this, so please feel free to close this issue if it's not appropriate.

I recently tried to run Cecilia from source on Debian 10 Stable, and I ran into a problem importing pyo. Specifically, the error I got was on l. 24 of `Resources/Widgets.py`:

```
from pyo.lib._wxwidgets import ControlSlider, HRangeSlider
ModuleNotFoundError: No module named 'pyo.lib'; 'pyo' is not a package
```

I found that this error occurred because on my system, rather than `lib` being a subdirectory of `pyo`, they both installed as one directory, `pyolib`. In order to run Cecilia, I had to change the original line to `from pyolib._wxwidgets import ControlSlider, HRangeSlider`.

I understand that this may no longer be the case on more up to date systems, but I thought I might let you know in case other people have this issue.

**Comment by belangeo** [comment]
Debian buster has version 0.9.1 in its repositories, it's rather old...

Either you compile pyo from source (which is not very complicated):

http://ajaxsoundstudio.com/pyodoc/compiling.html#debian-ubuntu-apt-get

Or you install pyo from sid repositories (version 1.0.3):

https://linuxaria.com/howto/how-to-install-a-single-package-from-debian-sid-or-debian-testing
