### ISSUE TITLE
Cecilia 5.4.1 compile error libasound wrong ELF class

### ISSUE THREAD

**Issue by poulpoulsen** [belangeo/cecilia5#105]
Hello,
after upgrading pyo to python 3.9 i tried to compile Cecilia.
I'm on Fedora 34.

But unfortunately it stops with error.
OSError: /home/held/.pyo/3.9_64/libs/libasound-fb332ab3.so.2.0.0: wrong ELF class: ELFCLASS32

Any ideas?
Regards
Poul

**Comment by belangeo** [comment]
The version of libasound installed on your system is apparently 32-bit, and pyo is looking for 64-bit libs. You should ensure that 64-bit version of libasound (and possibly jack and others) are actually available.

**Comment by poulpoulsen** [comment]
Hello,
ah yes. On my system both are installed. i dont know why.
After unstalling the i686 and delete the .pyo directory, it works.
Thanks
Poul

Now i will look for documentation, because first look the gui font is much too small and i cant see any configuration options.
