### ISSUE TITLE
Ajax Site not found

### ISSUE THREAD

**Issue by idkei** [belangeo/cecilia5#109]
Hi I've just learn about Cecilla and would like to check it out. Unfortunately Ajax site is not found or down. Is it possible to post the MAC OS binary here to download or maybe create a link to download the binary?

hope to hear from you soon. 

best

**Comment by belangeo** [comment]
Seems ok now!

**Comment by idkei** [comment]
err...not on my end, it just keep saying site not found.

**Comment by idkei** [comment]
so strange, tried on Firefox and it gives me an error but not on chrome. ok manage to accees site.
