### ISSUE TITLE
crash when switching modules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [belangeo/cecilia5#24]
```
Quick note with info from console attached. 

Cecilia 5.0.6
os x 10.7.4



```

Original issue reported on code.google.com by `eskenorh...@gmail.com` on 8 Jun 2012 at 1:06

Attachments:
* [cecilia5.0.6crash.rtf](https://storage.googleapis.com/google-code-attachments/cecilia5/issue-24/comment-0/cecilia5.0.6crash.rtf)

**Comment by belangeo** [comment]
This is fixed now with 5.2.0.
