### ISSUE TITLE
Cecilia 5 keeps crashing!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [belangeo/cecilia5#63]
```
What steps will reproduce the problem?
1. When a file is playing and you press stop seems to do it.
2. Will also crash at random at points.
3.

What is the expected output? What do you see instead?
Not to crash. Just see the window "programme has stopped responding" message

What version of the product are you using? On what operating system?
v 5.1.0 on Win 7

Please provide any additional information below.


```

Original issue reported on code.google.com by `nhug...@rsalink.co.uk` on 10 Sep 2014 at 9:28

Attachments:
* [Capture of cecilia crash.PNG](https://storage.googleapis.com/google-code-attachments/cecilia5/issue-63/comment-0/Capture of cecilia crash.PNG)
* [Capture of crash report for cecilia.PNG](https://storage.googleapis.com/google-code-attachments/cecilia5/issue-63/comment-0/Capture of crash report for cecilia.PNG)

**Comment by belangeo** [comment]
The crash should be fixed now with version 5.2.0.
