### ISSUE TITLE
5.3.2 can't boot on macOS Sierra

### ISSUE THREAD

**Issue by ahfontaine** [belangeo/cecilia5#72]
Opening Cecilia will result in a prompt asking to Terminate the program or to Open the console

Retrieved from console : 
Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

**Comment by belangeo** [comment]
Can you paste the complete output in Console.app after trying to launch Cecilia?

**Comment by ahfontaine** [comment]
default	20:40:59.844707 -0400	Cecilia5	subsystem: com.apple.coreaudio, category: AudioHAL_Client, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	20:41:00.000337 -0400	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	20:41:00.047955 -0400	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	20:41:00.048233 -0400	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	20:41:00.048697 -0400	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	20:41:00.070536 -0400	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	20:41:00.437397 -0400	Cecilia5	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	20:41:00.440340 -0400	launchservicesd	UNIX error exception: 22
default	20:41:00.440830 -0400	launchservicesd	MacOS error: -67062
default	20:41:00.488824 -0400	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	20:41:00.672292 -0400	Cecilia5	Cecilia5 Error
default	20:41:00.696221 -0400	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	20:41:00.702371 -0400	Cecilia5	subsystem: com.apple.AppKit, category: Layout, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 0, enable_private_data: 0
error	20:41:00.702445 -0400	Cecilia5	Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

**Comment by belangeo** [comment]
I found a link where the same problem happened with psychopy  on sierra and the workaround was to delete the app data and preferences. Can you try this, in a terminal window:

rm -r ~/.cecilia5

And relaunch Cecilia?

**Comment by ahfontaine** [comment]
All good! That was the issue.
