### ISSUE TITLE
Cecilia 5.3.2 - Preference pane not showing up

### ISSUE THREAD

**Issue by DominicThibault** [belangeo/cecilia5#74]
From the shortcut or the menu, the preference panel wont show up. 

OS X 10.11.6
On a shitty old macbook pro (13" mid 2011)

**Comment by DominicThibault** [comment]
This happens when Cecilia is opened for the first time. Re-launched Cecilia and now it's fine, the pref pane opens up.

**Comment by belangeo** [comment]
Maybe some backward non-compatible setting in the preferences... I'll investigate!
