### ISSUE TITLE
Cecilia 5.3.4 crash des l'ouverture

### ISSUE THREAD

**Issue by ThierryGauthier** [belangeo/cecilia5#81]
Cecilia 5.3.4 Crash à l'ouverture sur Mac Pro 5,1 Mac OS 10.13.1
Pourtant fonctionne bien sur MacBookPro 2017 OS 10.13.1

Comment enlever toute anciennes preferences ou fichier reliés au anciennes versions?
J'aimerais installer reinstaller «clean» la v 5.3.4...

Merci

[Cecilia Crash log.txt](https://github.com/belangeo/cecilia5/files/1452750/Cecilia.Crash.log.txt)

**Comment by belangeo** [comment]
Pour jeter les prefs, dans un terminal:

rm -r .cecilia5

Mon premier guess est que sur le mac pro il n'y a pas d'input audio et que ça fait planter le serveur audio. Par défaut, cecilia ne devrait pas chercher à ouvrir les ports audio en entrée.

**Comment by ThierryGauthier** [comment]
Je pense bien que tu as raison, mon driver de la MOTU fait de drôles de problème depuis 10.12. je crois que c'est ca.  Pour le moment, j'ai jeter les pref par le terminal, redémarrer et ca marche ca ouvre, je t'en redonne des nouvelles bientôt! Merci!!!!

**Comment by belangeo** [comment]
Excellent!
