### ISSUE TITLE
Crash when pressing play

### ISSUE THREAD

**Issue by Glitza** [belangeo/cecilia5#84]
I have reinstalled Cecilia 5 multiple times, nevertheless i keeps crashing. When loading a wav sample the following error message will pops up::
[Window Title]
Runtime Error!

[Main Instruction]
Cecilia can't run the current module, last valid module (or a random one if this failed too) will be reloaded.

[Content]
Traceback:

Traceback (most recent call last):
  File "Resources\audio.py", line 1804, in loadModule
    currentModule = module()
  File "C:\Program Files (x86)\Cecilia5\Resources\modules\Time\Pelletizer.c5", line 61, in __init__
  File "Resources\audio.py", line 749, in __init__
    self._addGraph(widget)
  File "Resources\audio.py", line 999, in _addGraph
    self._graphs[dic["name"]] = CeciliaGraph(dic)
  File "Resources\audio.py", line 703, in __init__
    self.table = LinTable(func, size=self.size)
  File "pyolib\tables.py", line 588, in __init__
  File "pyolib\_core.py", line 1596, in __init__
  File "pyolib\_core.py", line 823, in __init__
pyolib._core.PyoServerStateException: The Server must be booted before creating any audio object.

Please review this part of the code and reload the module:

#-----
                  'userSliders': {'cut': [2969.75317382813, 1, None, 1, None, None],
                                  'dens': [6.0, 0, None, 1, None, None],
#-----

[OK]

I´m using Windows 10 (64 bit). I´d really like to get this program working, but I can´t figure out if the issue is either about my hardware, my software or Cecilia itself.

Thank you, Glitza.

**Comment by belangeo** [comment]
Mismatch between cecilia's audio settings and system audio settings would be my first guess. Can you open cecilia's preferences, in the audio tab, and change the output device to "Primary Sound Driver" (uncheck the audio device checkbox if checked). This should resolve the problem.

**Comment by Glitza** [comment]
Oh. My. God. How can it be so easy! I was trying for days but why assuming a zebra, most likely it´s just a horse, isn´t it?
I got lots of outputs and changed to my primary sound driver, which has actually the same name as the one set with launch and I don´t know why but nevermind. A little confusing but thanks to your help it´s working and I can finally hear something.

Much appreciate, Glitza.
