### ISSUE TITLE
Parameters missing and automation not working

### ISSUE THREAD

**Issue by JVanBuskirk** [belangeo/cecilia5#85]
Hi,
  This may have been done on purpose, but the loopmode and other parameters for the sampler are no longer available in source sound controls.  Automation of the post-processing effects does not work  currently either.

On a side note, I added a "pan" effect for the post-processing plugins.  If you are interested, I can send a pull-request.

**Comment by belangeo** [comment]
Hi,
Can you be more specific? Both are working as expected here on Debian, lastest sources.
Olivier

**Comment by JVanBuskirk** [comment]
I see my mistake on the loopmode.  I was looking at the table based modules, Granulator, etc..  I didn't think it through.

Automation worked when I tried just now.  I'm unsure of what the problem was.  I can't replicate it today.  I'll let you know if it happens again.

Sorry for the noise.
