### ISSUE TITLE
No Input window panel 

### ISSUE THREAD

**Issue by zzzzzij** [belangeo/cecilia5#87]
I download a mac os version and there is no input channel in my interface. 
Any idea how to fix it?...
<img width="995" alt="Screen Shot 2019-04-05 at 5 18 00 PM" src="https://user-images.githubusercontent.com/49315684/55638135-cca4bc00-57c6-11e9-9d2b-67e0f0ad1ef0.png">

**Comment by belangeo** [comment]
This is the additive synthesis module, which does not use an input signal. Choose an « fx » module and you will see the input panel.

**Comment by zzzzzij** [comment]
Super...Thank you!
