### ISSUE TITLE
No module named 'pyolib' using pyo==1.0.0

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [belangeo/cecilia5#90]
Environment:
* python 3.6.9
* wxpython 4.0.1
* numpy 1.17.2
* **pyo 1.0.0**

After running `python3.6 Cecilia5.py`, it prompted `No module named 'pyolib'`.

I tried to find pyo==0.9.0, but I can find it nowhere. Would you like to fix the dependency since `pyo==1.0.0` has been released?

**Comment by belangeo** [comment]
Did you update you cecilia5 sources? If it searches for pyolib, then your not up-to-date. Just checkout the last sources to fix it. I'll update the README...

**Comment by ZenithalHourlyRate** [comment]
No, I used the tarball released Cecilia 5.3.5 at [official website](http://ajaxsoundstudio.com/downloads/Cecilia5_5.3.5-src.tar.bz2)

By using this git repo I can successfully open it.

**Comment by indeedwatson** [comment]
I have the same problem, downloading Cecilia 5.3.5 from either the website or the `Releases` in this repo.

**Comment by belangeo** [comment]
If you want to launch Cecilia from sources, you'll have to use the latest sources on git. Otherwise, the 5.3.5 tarball is now incompatible with recent versions of pyo.

Or, if you are on MacOS or Windows, you just download the binary installer...

**Comment by indeedwatson** [comment]
Ah nevermind I thought by sources you meant releases. Surprised it's not in AUR. Anyway, got it working, thanks!
