### ISSUE TITLE
Cecilia 5.4.0 crash after startup on Windows 10

### ISSUE THREAD

**Issue by icelizarrd** [belangeo/cecilia5#93]
I'm trying to run the Cecilia 5.4.0 binaries on Windows 10 (x64). Unfortunately, the application closes/crashes shortly after opening it.

The console opens up, it states that couldn't find a preferences file and will use defaults. Then the splash screen appears, and the program quits/crashes shortly thereafter.

I tried running as administrator in case it was some kind of permissions issue but that didn't help.

**Comment by belangeo** [comment]
Hi, can you launch the application from the command prompt to see if there is an error message printed before the crash. In a command prompt, go to the Cecilia5 folder and execute the exe:

```
cd "Something\like\Program Files(x64)\Cecilia5"
Cecilia5.exe

```

**Comment by icelizarrd** [comment]
Hi there. I tried running it from the command prompt, but it prints nothing before closing.

**Comment by belangeo** [comment]
Ok. If you are willing, you can follow the steps in this link to see if there is an informative crash log.

https://www.supereasy.com/how-to-view-crash-logs-in-windows-10/

If you don't want to do it, I have a student with, seemingly, a similar problem. I'll try to debug it on his computer next week and then, I can get back to you with, hopefully, a solution!

**Comment by icelizarrd** [comment]
Sure thing. Turns out there is an indeed an error in the log:


Log Name:      Application
Source:        Application Error
Date:          1/17/2020 4:53:39 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-AL0QJD9
Description:
Faulting application name: Cecilia5.exe, version: 0.0.0.0, time stamp: 0x5d24a292
Faulting module name: libportmidi.dll, version: 0.0.0.0, time stamp: 0xa450a440
Exception code: 0xc0000005
Fault offset: 0x0000000000001812
Faulting process id: 0x2a34
Faulting application start time: 0x01d5cd99b5553cc8
Faulting application path: C:\Program Files (x86)\Cecilia5\Cecilia5.exe
Faulting module path: C:\Users\nkh\AppData\Local\Temp\_MEI111802\libportmidi.dll
Report Id: f350eafd-1773-4672-957a-3d7b046ad359
Faulting package full name: 
Faulting package-relative application ID: 



Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-18T00:53:39.193292800Z" />
    <EventRecordID>6415</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-AL0QJD9</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Cecilia5.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5d24a292</Data>
    <Data>libportmidi.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>a450a440</Data>
    <Data>c0000005</Data>
    <Data>0000000000001812</Data>
    <Data>2a34</Data>
    <Data>01d5cd99b5553cc8</Data>
    <Data>C:\Program Files (x86)\Cecilia5\Cecilia5.exe</Data>
    <Data>C:\Users\nkh\AppData\Local\Temp\_MEI111802\libportmidi.dll</Data>
    <Data>f350eafd-1773-4672-957a-3d7b046ad359</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by belangeo** [comment]
Ok, that does not tell much but now I know it has to do with the midi library... I'll see what I can do.

**Comment by caecos** [comment]
Same for me Cecilia crash on start up...

**Comment by caecos** [comment]
Are you still maintaining Cecilia?

**Comment by belangeo** [comment]
To be honest, I really don't have much time to give to Cecilia... I spent a lot of hours during the holidays and I was not planning to work on it for a while. My two windows computer don't show this behaviour so it's a little bit hard to investigate. As soon as I cross the path of one of those, I'll see what I can do.

**Comment by mattiabruni** [comment]
I have the same problem, both with the installer and with the source from git.
If I try to run the 3.3.5 version from the command prompt I get:

Preferences file not found. Using defaults...

Traceback (most recent call last):
  File "cecilia5.py", line 25, in <module>
    from Resources import audio, CeciliaMainFrame
  File "C:\Users\pc2\Desktop\Audio Editor\cecilia5-5.3.5\Resources\CeciliaMainFrame.py", line 25, in <module>
    import Resources.PreferencePanel as PreferencePanel
  File "C:\Users\pc2\Desktop\Audio Editor\cecilia5-5.3.5\Resources\PreferencePanel.py", line 24, in <module>
    from .Widgets import *
  File "C:\Users\pc2\Desktop\Audio Editor\cecilia5-5.3.5\Resources\Widgets.py", line 24, in <module>
    from pyolib._wxwidgets import ControlSlider, HRangeSlider
ModuleNotFoundError: No module named 'pyolib'

Windows 10 version is 1803, I will see if anything changes after I update.

**Comment by belangeo** [comment]
Old Cecilia sources are not compatible with latest pyo (1.0.0+). Just update your Cecilia to the latest git if you want to run it from sources.

**Comment by caecos** [comment]
I have tried it and it crashed as well… tout plante ???

**Comment by joncarr** [comment]
Same Issue, Crash on Startup, Windows 10. Is there build instructions for Win10 somewhere? maybe I can just build it from source to see if that fixes my issue?

**Comment by belangeo** [comment]
Nothing to build, just install the requirements and run it from a command prompt. See instructions here:

http://ajaxsoundstudio.com/cecilia5doc/src/intro/requirements.html#running-cecilia-from-the-lastest-sources

**Comment by caecos** [comment]
Still not working:

$ python3 cecilia5.py
Traceback (most recent call last):
  File "cecilia5.py", line 23, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

**Comment by belangeo** [comment]
wxPython is not installed...

`python3 -m pip install -U wxpython
`

**Comment by caecos** [comment]
c:\Users\caeco\AppData\Local\Programs\Python\Python38>pip install -U wxPython
Requirement already up-to-date: wxPython in c:\users\caeco\appdata\local\programs\python\python38\lib\site-packages (4.0.7.post2)
Requirement already satisfied, skipping upgrade: numpy; python_version >= "3.0" in c:\users\caeco\appdata\local\programs\python\python38\lib\site-packages (from wxPython) (1.18.1)
Requirement already satisfied, skipping upgrade: six in c:\users\caeco\appdata\local\programs\python\python38\lib\site-packages (from wxPython) (1.14.0)
Requirement already satisfied, skipping upgrade: pillow in c:\users\caeco\appdata\local\programs\python\python38\lib\site-packages (from wxPython) (7.0.0)

**Comment by belangeo** [comment]
Are you sure that the `python3` command targets the python 3.8 installation for which you have installed wxpython ?

**Comment by caecos** [comment]
Shall I try python38 cecilia5.py ?

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Tuesday, March 10, 2020 10:38:08 PM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


Are you sure that the python3 command targets the python 3.8 installation for which you have installed wxpython ?

**Comment by belangeo** [comment]
I usually use the python launcher on Windows to ensure that I use the good one.
`py -3.8 -m pip install -U wxPython
`
then, in cecilia's folder:
`py -3.8 Cecilia5.py
`

**Comment by caecos** [comment]
On Windows 10, Python 2.7.x is installed in C:/python27 and Python 3.x.x in the appData folder...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Marc Demers <caecos@hotmail.ca>
Envoyé : Tuesday, March 10, 2020 10:42:31 PM
À : belangeo/cecilia5 <reply@reply.github.com>; belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)

Shall I try python38 cecilia5.py ?

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Tuesday, March 10, 2020 10:38:08 PM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


Are you sure that the python3 command targets the python 3.8 installation for which you have installed wxpython ?

**Comment by belangeo** [comment]
No need to worry about the location of the different versions of python, the python launcher (`py -x.x`) will handle that for you!

**Comment by caecos** [comment]
Ok I will give a try tomorrow... how to you call the python launcher?

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Tuesday, March 10, 2020 10:49:28 PM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


No need to worry about the location of the different versions of python, the python launcher (py -x.x) will handle that for you!

**Comment by caecos** [comment]
Ok it works

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Marc Demers <caecos@hotmail.ca>
Envoyé : Tuesday, March 10, 2020 10:55:50 PM
À : belangeo/cecilia5 <reply@reply.github.com>; belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)

Ok I will give a try tomorrow... how to you call the python launcher?

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Tuesday, March 10, 2020 10:49:28 PM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


No need to worry about the location of the different versions of python, the python launcher (py -x.x) will handle that for you!

**Comment by caecos** [comment]
non

$ py -3.8 cecilia5.py
Segmentation fault

**Comment by belangeo** [comment]
Can you try:

`py -3.8 -X dev Cecilia5.py
`

**Comment by caecos** [comment]
$ py -3.8 -X dev Cecilia5.py
Windows fatal exception: access violation

Current thread 0x00003218 (most recent call first):
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\pyo\lib\server.py", line 820 in boot
  File "C:\msys64\home\caeco\cecilia5\Resources\audio.py", line 1640 in boot
  File "C:\msys64\home\caeco\cecilia5\Resources\audio.py", line 1760 in openCecFile
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaLib.py", line 755 in openCeciliaFile
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaMainFrame.py", line 227 in onOpen
  File "Cecilia5.py", line 66 in onStart
  File "C:\msys64\home\caeco\cecilia5\Resources\splash.py", line 98 in OnClose
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 3410 in Notify
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2254 in Notify
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2167 in MainLoop
  File "Cecilia5.py", line 117 in <module>
Segmentation fault

**Comment by MSavioti** [comment]
Crashing for me on Windows 10 too...

**Comment by kongehund** [comment]
Same problem here. I tried running several earlier versions via the GitHub repository history to see if they would run, but the ones I tried are either pyo-incompatible or have the same crashing problem. Version 5.3.4 gives me a pyolib error and version 5.4.5 upwards crashes on startup.

Are there any self-containing Windows 10 binaries available for download for even earlier versions of Cecilia, say, some version of Cecilia 4?  I can't find any on your website.

@belangeo

**Comment by ggrmd** [comment]
It started crashing at launch yesterday for me as well on Win 10 :

$ py -3.8 -X dev Cecilia5.py
Windows fatal exception: access violation

Current thread 0x00003a94 (most recent call first):
  File "C:\Users\geoff\AppData\Local\Programs\Python\Python38\lib\site-packages\pyo\lib\server.py", line 820 in boot
  File "C:\Users\geoff\cecilia5\Resources\audio.py", line 1640 in boot
  File "C:\Users\geoff\cecilia5\Resources\audio.py", line 1760 in openCecFile
  File "C:\Users\geoff\cecilia5\Resources\CeciliaLib.py", line 755 in openCeciliaFile
  File "C:\Users\geoff\cecilia5\Resources\CeciliaMainFrame.py", line 227 in onOpen
  File "Cecilia5.py", line 66 in onStart
  File "C:\Users\geoff\cecilia5\Resources\splash.py", line 98 in OnClose
  File "C:\Users\geoff\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 3410 in Notify
  File "C:\Users\geoff\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2254 in Notify
  File "C:\Users\geoff\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2167 in MainLoop
  File "Cecilia5.py", line 117 in <module>
Segmentation fault

**Comment by jjbabydarling** [comment]
I'm having a similar problem. Going back to 5.3.5 for now.

Would you recommend trying to run it from source code to get around this issue... to someone who is a novice at programming languages in general?

Thank you

**Comment by ggrmd** [comment]
I've tried running it from source code, but I still have the same problem. This is how I got the log I posted above (with dev option).

**Comment by jjbabydarling** [comment]
Ok thanks for the response. 👍

**Comment by tjspeakman** [comment]
hello, I've just installed Cecilia 5.4 on my new windows 10 x64 computer and it launches only when my roland a-49 midi keyboard is unplugged. As a disclaimer I'm not at all adept at coding, I just thought this information could potentially help. Cecilia is unable to find the keyboard if I plug it in after launching. Will be following this thread, thanks!

**Comment by caecos** [comment]
With my midi keyboard connected or not, Cecilia crashes anyhow…

Marc


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : tjspeakman<mailto:notifications@github.com>
Envoyé le :lundi 27 avril 2020 19:12
À : belangeo/cecilia5<mailto:cecilia5@noreply.github.com>
Cc : caecos<mailto:caecos@hotmail.ca>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


hello, I've just installed Cecilia 5.4 on my new windows 10 x64 computer and it launches only when my roland a-49 midi keyboard is unplugged. As a disclaimer I'm not at all adept at coding, I just thought this information could potentially help. Cecilia is unable to find the keyboard if I plug it in after launching. Will be following this thread, thanks!

**Comment by hlzr** [comment]
I am also having this issue.

**Comment by user26062000** [comment]
anybody come round with this? Im having this issue!!

**Comment by caecos** [comment]
No...I'm still waiting...

**Comment by bradrn** [comment]
I’m having the same issue. Interestingly, it only occurs when my keyboard is plugged in — otherwise it works fine. As with @icelizarrd earlier in the thread, Event Viewer reports that the issue appears to be with `libportmidi.dll`.

**Comment by user26062000** [comment]
i have various midi inputs. not sure how id get around it, because my audio interface has 2 midi ins and outs. this is so damn annoying! wish there'd be a response from ajax. tried emailing them numerous times but no response...

**Comment by belangeo** [comment]
You should not write to ajax about cecilia issues, I rarely see those messages...
As I said earlier in this thread, I don't have much time to spend on Cecilia, but first of all, I can't repro on any of my Windows computer (one running win7, two running win10). I'll debug this issue as sson as I found a computer which has this behavior.

**Comment by caecos** [comment]
Cecilia is running of yours Windows PC!? Quite strange...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Wednesday, July 22, 2020 8:37:12 AM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


You should not write to ajax about cecilia issues, I rarely see those messages...
As I said earlier in this thread, I don't have much time to spend on Cecilia, but first of all, I can't repro on any of my Windows computer (one running win7, two running win10). I'll debug this issue as sson as I found a computer which has this behavior.

**Comment by belangeo** [comment]
Perfectly on all three...!

**Comment by user26062000** [comment]
hi olivier,
do these computers youve tested on have midi devices plugged in? this seems to be the defining factor

**Comment by caecos** [comment]
As for me, I have MIDI devices (keyboard and controllers) connected to my laptop...pluged or unpluged...Cecilia crashed anyhow...

**Comment by icelizarrd** [comment]
Just adding an extra discovery here: I've been using "MIDI loopback" software to permit sending MIDI from one application to another within Windows. (Tobias Erichsen's "loopMIDI" is the name). 

It turns out that terminating the loopMIDI process actually allows me to start Cecilia successfully (i.e. it no longer crashes).

So maybe for debugging purposes the crashes could be replicated by installing and running loopMIDI? It's freely available at https://www.tobias-erichsen.de/software/loopmidi.html

**Comment by belangeo** [comment]
Anyone running Cecilia from sources willing to try with this modified pyo installer and report back here? It uses an updated portmidi library. Thanks!

https://www.dropbox.com/s/4w4z4av64fvpsq2/pyo-1.0.1-cp36-cp36m-win_amd64.whl?dl=0

https://www.dropbox.com/s/s2d8ox6qvdwnqq8/pyo-1.0.1-cp37-cp37m-win_amd64.whl?dl=0

https://www.dropbox.com/s/1bfw8xcqbndzx5b/pyo-1.0.1-cp38-cp38-win_amd64.whl?dl=0

**Comment by caecos** [comment]
I've just tried it and it still crashing:

$ py -3.8 -X dev Cecilia5.py
Windows fatal exception: access violation

Current thread 0x00002538 (most recent call first):
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\pyo\lib\server.py", line 820 in boot
  File "C:\msys64\home\caeco\cecilia5\Resources\audio.py", line 1640 in boot
  File "C:\msys64\home\caeco\cecilia5\Resources\audio.py", line 1760 in openCecFile
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaLib.py", line 755 in openCeciliaFile
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaMainFrame.py", line 227 in onOpen
  File "Cecilia5.py", line 66 in onStart
  File "C:\msys64\home\caeco\cecilia5\Resources\splash.py", line 98 in OnClose
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 3508 in Notify
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2311 in Notify
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2224 in MainLoop
  File "Cecilia5.py", line 117 in <module>
Segmentation fault

**Comment by caecos** [comment]
Question tribale: on fait quoi avec la fichier de DropBox?

**Comment by belangeo** [comment]
These are zipped releases to install with pip. Download the .whl file for your python version and then, in a command prompt:

```
cd path\to\the\whl_file
py -3.8 -m pip install --force-reinstall pyo-1.0.1-cp38-cp38-win_amd64.whl

```
After that, try to launch Cecilia...

**Comment by belangeo** [comment]
Any news? If it works as expected, I will proceed and prepare a new releases for pyo and Cecilia!

**Comment by caecos** [comment]
I have not be able to try it but a new release will do no harms...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Tuesday, August 11, 2020 12:39:50 PM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


Any news? If it works as expected, I will proceed and prepare a new releases for pyo and Cecilia!

**Comment by belangeo** [comment]
Did you have any problems installing pyo? I'm not in a rush, I still need a few days before I'm ready to release a new version of pyo...

**Comment by caecos** [comment]
Pyo installation went fine and Pyo is working...I will try Cecilia tonight and let you know...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Olivier Bélanger <notifications@github.com>
Envoyé : Tuesday, August 11, 2020 2:50:25 PM
À : belangeo/cecilia5 <cecilia5@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Comment <comment@noreply.github.com>
Objet : Re: [belangeo/cecilia5] Cecilia 5.4.0 crash after startup on Windows 10 (#93)


Did you have any problems installing pyo? I'm not in a rush, I still need a few days before I'm ready to release a new version of pyo...

**Comment by belangeo** [comment]
Thank you! It's really appreciated!

**Comment by caecos** [comment]
Doesn't work... ePyo neither...Cecilia5 get stucked with the opening image rectangle (ear binding etc...)...I have tried many ways to start Cecilia but my laptop freezed after the last one...

**Comment by belangeo** [comment]
This looks like something else... What does the console say when you start with the flag -X dev ?

**Comment by caecos** [comment]
py -3.8 Cecilia5.py or  py -3.8 -X dev Cecilia5.py, here the console message:

$ py -3.8 Cecilia5.py
Traceback (most recent call last):
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2311, in Notify
    self.notify()
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 3508, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "C:\msys64\home\caeco\cecilia5\Resources\splash.py", line 98, in OnClose
    self.callback()
  File "Cecilia5.py", line 66, in onStart
    ceciliaMainFrame.onOpen(os.path.join(MODULES_PATH, category, file), True)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaMainFrame.py", line 227, in onOpen
    CeciliaLib.openCeciliaFile(self, event, builtin)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaLib.py", line 755, in openCeciliaFile
    if not getVar("audioServer").openCecFile(cecFilePath):
  File "C:\msys64\home\caeco\cecilia5\Resources\audio.py", line 1788, in openCecFile
    CeciliaLib.getVar("mainFrame").onUpdateInterface(None)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaMainFrame.py", line 305, in onUpdateInterface
    ceciliaInterface = CeciliaInterface.CeciliaInterface(None, title='Interface - %s' % title, mainFrame=self)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaInterface.py", line 53, in __init__
    self.controlPanel = Control.CECControl(self, -1)
  File "C:\msys64\home\caeco\cecilia5\Resources\Control.py", line 71, in __init__
    self.sizerMain.Add(self.tabs, 1, wx.EXPAND | wx.ALIGN_CENTER | wx.ALL, 0)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(1453)

**Comment by belangeo** [comment]
That’s what I though... You updated wxpython to 4.1 (breaks backward compatibilité). It’s already fixed on my computer... I’ll push these changes when I get back home.

**Comment by caecos** [comment]
Last line was missing:
$ py -3.8 Cecilia5.py
Traceback (most recent call last):
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 2311, in Notify
    self.notify()
  File "C:\Users\caeco\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\core.py", line 3508, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "C:\msys64\home\caeco\cecilia5\Resources\splash.py", line 98, in OnClose
    self.callback()
  File "Cecilia5.py", line 66, in onStart
    ceciliaMainFrame.onOpen(os.path.join(MODULES_PATH, category, file), True)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaMainFrame.py", line 227, in onOpen
    CeciliaLib.openCeciliaFile(self, event, builtin)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaLib.py", line 755, in openCeciliaFile
    if not getVar("audioServer").openCecFile(cecFilePath):
  File "C:\msys64\home\caeco\cecilia5\Resources\audio.py", line 1788, in openCecFile
    CeciliaLib.getVar("mainFrame").onUpdateInterface(None)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaMainFrame.py", line 305, in onUpdateInterface
    ceciliaInterface = CeciliaInterface.CeciliaInterface(None, title='Interface - %s' % title, mainFrame=self)
  File "C:\msys64\home\caeco\cecilia5\Resources\CeciliaInterface.py", line 53, in __init__
    self.controlPanel = Control.CECControl(self, -1)
  File "C:\msys64\home\caeco\cecilia5\Resources\Control.py", line 71, in __init__
    self.sizerMain.Add(self.tabs, 1, wx.EXPAND | wx.ALIGN_CENTER | wx.ALL, 0)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(1453) in wxGridSizer::DoInsert(): wxEXPAND flag will be overridden by alignment flags

**Comment by caecos** [comment]
Good, I will try Cecilia once fixed...regards...

**Comment by belangeo** [comment]
Sources in git are updated with the fixes for wxpython 4.1 compatibility!

**Comment by belangeo** [comment]
To try with latest sources, all is needed is:

```
cd path\to\cecilia5
git pull
py -3.8 Cecilia5.py

```

**Comment by caecos** [comment]
It works...great...many thanks...

**Comment by belangeo** [comment]
Good! Will do an official release soon.
